

  - name: ytbuddy1-client
    type: web
    runtime: node
    buildCommand: npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
  - key: VITE_API_URL
    value: https://ytbuddy1.onrender.com  # Your backend URL